Update Jenkinspipe

diff --git a/Jenkinspipe b/Jenkinspipe
--- a/Jenkinspipe
+++ b/Jenkinspipe
@@ -1,28 +1,47 @@
-stages {
-    stage('Clone Repository') {
-        steps {
-            git branch: 'main', url: 'https://github.com/Veeresh85/My-Jenkins-project.git'
+pipeline {
+    agent any
+
+    environment {
+        MAVEN_HOME = '/usr/share/maven'
+        JAVA_HOME = '/usr/lib/jvm/java-17-openjdk-amd64'
+        TOMCAT_HOME = '/home/veeresh/apache-tomcat-9.0.99'
+    }
+
+    stages {
+        stage('Clone Repository') {
+            steps {
+                git branch: 'main', url: 'https://github.com/Veeresh85/My-Jenkins-project.git'
+            }
+        }
+
+        stage('Build') {
+            steps {
+                sh 'mvn clean package'
+            }
+        }
+
+        stage('Test') {
+            steps {
+                sh 'mvn test'
+            }
+        }
+
+        stage('Deploy to Tomcat') {
+            steps {
+                sh 'cp target/*.war $TOMCAT_HOME/webapps/'
+                sh '$TOMCAT_HOME/bin/shutdown.sh || true'
+                sleep(time:10, unit:'SECONDS')
+                sh '$TOMCAT_HOME/bin/startup.sh'
+            }
         }
     }
 
-    stage('Build') {
-        steps {
-            sh "mvn clean package"
+    post {
+        success {
+            echo 'Deployment successful!'
         }
-    }
-
-    stage('Test') {
-        steps {
-            sh "mvn test"
-        }
-    }
-
-    stage('Deploy to Tomcat') {
-        steps {
-            sh "cp target/*.war $TOMCAT_HOME/webapps/"
-            sh "$TOMCAT_HOME/bin/shutdown.sh || true"
-            sleep(time:10, unit:"SECONDS")
-            sh "$TOMCAT_HOME/bin/startup.sh"
+        failure {
+            echo 'Build or deployment failed!'
         }
     }
 }
